	$(document).ready(function(){

		$('body').append('<div id="callback-button">'
			+ '<a href="#"'
				+ 'style="'
					+ 'position: fixed; bottom: 45px; right: 50px;'
					+ 'font-weight: bold; background-color: #f89a14; color: #FFFFFF;'
					+ 'padding: 0 30px;	border-radius: 20px !important;'
				  + 'border-color: #eeeeee;'
			    + 'font-size: 16px;'
			    + 'font-family: sans-serif;'
			    + 'text-align: center;'
			    + 'line-height: 40px;'
			    + 'height: 40px;'
			    + 'margin: 0;'
			    + 'display: inline-block;'
			    + 'cursor: pointer;'
			    + 'border: none;'
			    + 'box-sizing: border-box;'
			    + 'transition-property: all;'
					+ 'max-width: 320px;'
					+ 'min-width: 158.25px;'
    			+ 'transition-duration: .3s;"'
					+ '>Call Me Back</a>'
		  + '</div>');

		$('body').append('<div id="callback-widget" style="'
					+ 'position: fixed;'
					+ 'bottom: 45px;'
					+ 'right: 10px;'
					+ 'max-width: 320px;'
					+ 'min-width: 320px;'
					+ 'width: 320px;'
					+ 'height: 500px;'
					+ 'background-color: #FFFFFF;'
					+ 'color: #000000;'
					+ 'font-family: Lato, sans-serif;'
					+ 'font-size: 14px;'
    			+ 'line-height: 2;'
    			+ 'color: #333;'
					+ 'display: none;'
					+ 'border-radius: 5px;">'
					+ '<style>'
					+ '#callback-widget label,input {'
					+ 'width: 100%;'
					+ 'height: 30px;'
					+ '}'
					+ '#callback-widget label {'
					+ 'margin-bottom: 0;'
					+ '}'
					+ '#callback-widget select {'
					+ 'height: 30px;'
					+ '}'
					+ '#callback-widget.left { left: 40px; }'
					+ '#callback-widget.center { margin: auto; }'
					+ '</style>'
				+ '<form border="0" name="contact" style="padding: 20px;" method="POST" action="" onsubmit="return(validate());">'
						+ '<div style="margin:7px 0 7px 0;" class="above-text">'
						+ '<b>Please fill up the form below.</b>'
						+ '</div>'
						+ '<!--Full name-->'
							+ '<label>Full Name *</label>'
							+ '<input type="text" class="input" maxlength="35" name="name" value="">'
						+ '<!--Email address-->'
							+ '<label>Email Address *</label>'
							+ '<input type="text" class="input" maxlength="45" name="email" value="">'
						+ '<!--Phone number-->'
							+ '<label>Your phone number *</label>'
							+ '<input type="text" name="phone" class="input" value="" maxlength="30">'
						+ '<!--Best to call-->'
							+ '<label>Best time to call</label>'
							+ '<select style="width: 48%; margin-bottom: 5px; margin-right: 10px;" name="time_month">'
								+ '<option value="1">1</option>'
								+ '<option value="2">2</option>'
								+ '<option value="3">3</option>'
								+ '<option value="4">4</option>'
								+ '<option value="5">5</option>'
								+ '<option value="6">6</option>'
								+ '<option value="7">7</option>'
								+ '<option value="8">8</option>'
								+ '<option value="9">9</option>'
								+ '<option value="10">10</option>'
								+ '<option value="11">11</option>'
								+ '<option value="12">12</option>'
							+ '</select>'
							+ '<select style="width: 48%; margin-bottom: 5px;" name="time_day">'
								+ '<option value="1">1</option>'
								+ '<option value="2">2</option>'
								+ '<option value="3">3</option>'
								+ '<option value="4">4</option>'
								+ '<option value="5">5</option>'
								+ '<option value="6">6</option>'
								+ '<option value="7">7</option>'
								+ '<option value="8">8</option>'
								+ '<option value="9">9</option>'
								+ '<option value="10">10</option>'
								+ '<option value="11">11</option>'
								+ '<option value="12">12</option>'
								+ '<option value="13">13</option>'
								+ '<option value="14">14</option>'
								+ '<option value="15">15</option>'
								+ '<option value="16">16</option>'
								+ '<option value="17">17</option>'
								+ '<option value="18">18</option>'
								+ '<option value="19">19</option>'
								+ '<option value="20">20</option>'
								+ '<option value="21">21</option>'
								+ '<option value="22">22</option>'
								+ '<option value="23">23</option>'
								+ '<option value="24">24</option>'
								+ '<option value="25">25</option>'
								+ '<option value="26">26</option>'
								+ '<option value="27">27</option>'
								+ '<option value="28">28</option>'
								+ '<option value="29">29</option>'
								+ '<option value="30">30</option>'
								+ '<option value="31">31</option>'
							+ '</select>'
							+ '<select style="width: 48%; margin-bottom: 5px; margin-right: 10px;" name="time">'
								+ '<option value="00:00 (Midnight)">12:00 A.M.</option>'
								+ '<option value="00:30 (12:30 A.M.)">12:30 A.M.</option>'
								+ '<option value="01:00 (1:00 A.M.)">1:00 A.M.</option>'
								+ '<option value="01:30 (1:30 A.M.)">1:30 A.M.</option>'
								+ '<option value="02:00 (2:00 A.M.)">2:00 A.M.</option>'
								+ '<option value="02:30 (2:30 A.M.)">2:30 A.M.</option>'
								+ '<option value="03:00 (3:00 A.M.)">3:00 A.M.</option>'
								+ '<option value="03:30 (3:30 A.M.)">3:30 A.M.</option>'
								+ '<option value="04:00 (4:00 A.M.)">4:00 A.M.</option>'
								+ '<option value="04:30 (4:30 A.M.)">4:30 A.M.</option>'
								+ '<option value="05:00 (5:00 A.M.)">5:00 A.M.</option>'
								+ '<option value="05:30 (5:30 A.M.)">5:30 A.M.</option>'
								+ '<option value="06:00 (6:00 A.M.)">6:00 A.M.</option>'
								+ '<option value="06:30 (6:30 A.M.)">6:30 A.M.</option>'
								+ '<option value="07:00 (7:00 A.M.)">7:00 A.M.</option>'
								+ '<option value="07:30 (7:30 A.M.)">7:30 A.M.</option>'
								+ '<option value="08:00 (8:00 A.M.)">8:00 A.M.</option>'
								+ '<option value="08:30 (8:30 A.M.)">8:30 A.M.</option>'
								+ '<option value="09:00 (9:00 A.M.)">9:00 A.M.</option>'
								+ '<option value="09:30 (9:30 A.M.)">9:30 A.M.</option>'
								+ '<option value="10:00 (10:00 A.M.)">10:00 A.M.</option>'
								+ '<option value="10:30 (10:30 A.M.)">10:30 A.M.</option>'
								+ '<option value="11:00 (11:00 A.M.)">11:00 A.M.</option>'
								+ '<option value="11:30 (11:30 A.M.)">11:30 A.M.</option>'
								+ '<option value="12:00 (12:00 (Noon)" selected="">12:00 P.M.</option>'
								+ '<option value="12:30 (12:30 P.M.)">12:30 P.M.</option>'
								+ '<option value="13:00 (1:00 P.M.)">1:00 P.M.</option>'
								+ '<option value="13:30 (1:30 P.M.)">1:30 P.M.</option>'
								+ '<option value="14:00 (2:00 P.M.)">2:00 P.M.</option>'
								+ '<option value="14:30 (2:30 P.M.)">2:30 P.M.</option>'
								+ '<option value="15:00 (3:00 P.M.)">3:00 P.M.</option>'
								+ '<option value="15:30 (3:30 P.M.)">3:30 P.M.</option>'
								+ '<option value="16:00 (4:00 P.M.)">4:00 P.M.</option>'
								+ '<option value="17:00 (5:00 P.M.)">5:00 P.M.</option>'
								+ '<option value="16:30 (4:30 P.M.)">4:30 P.M.</option>'
								+ '<option value="17:30 (5:30 P.M.)">5:30 P.M.</option>'
								+ '<option value="18:00 (6:00 P.M.)">6:00 P.M.</option>'
								+ '<option value="18:30 (6:30 P.M.)">6:30 P.M.</option>'
								+ '<option value="19:00 (7:00 P.M.)">7:00 P.M.</option>'
								+ '<option value="19:30 (7:30 P.M.)">7:30 P.M.</option>'
								+ '<option value="20:00 (8:00 P.M.)">8:00 P.M.</option>'
								+ '<option value="20:30 (8:30 P.M.)">8:30 P.M.</option>'
								+ '<option value="21:00 (9:00 P.M.)">9:00 P.M.</option>'
								+ '<option value="21:30 (9:30 P.M.)">9:30 P.M.</option>'
								+ '<option value="22:00 (10:00 P.M.)">10:00 P.M.</option>'
								+ '<option value="22:30 (10:30 P.M.)">10:30 P.M.</option>'
								+ '<option value="23:00 (11:00 P.M.)">11:00 P.M.</option>'
								+ '<option value="23:30 (11:30 P.M.)">11:30 P.M.</option>'
							+ '</select>'
							+ '<select style="width: 48%; margin-bottom: 5px;" name="time_gmt">'
								+ '<option value="GMT-1">GMT-1</option>'
								+ '<option value="GMT-2">GMT-2</option>'
								+ '<option value="GMT-3">GMT-3</option>'
								+ '<option value="GMT-4">GMT-4</option>'
								+ '<option value="GMT-5">GMT-5</option>'
								+ '<option value="GMT-6">GMT-6</option>'
								+ '<option value="GMT-7">GMT-7</option>'
								+ '<option value="GMT-8">GMT-8</option>'
								+ '<option value="GMT-9">GMT-9</option>'
								+ '<option value="GMT-10">GMT-10</option>'
								+ '<option value="GMT-11">GMT-11</option>'
								+ '<option value="GMT-12">GMT-12</option>'
								+ '<option value="GMT" selected="">GMT</option>'
								+ '<option value="GMT+1">GMT+1</option>'
								+ '<option value="GMT+2">GMT+2</option>'
								+ '<option value="GMT+3">GMT+3</option>'
								+ '<option value="GMT+4">GMT+4</option>'
								+ '<option value="GMT+5">GMT+5</option>'
								+ '<option value="GMT+6">GMT+6</option>'
								+ '<option value="GMT+7">GMT+7</option>'
								+ '<option value="GMT+8">GMT+8</option>'
								+ '<option value="GMT+9">GMT+9</option>'
								+ '<option value="GMT+10">GMT+10</option>'
								+ '<option value="GMT+11">GMT+11</option>'
								+ '<option value="GMT+12">GMT+12</option>'
							+ '</select>'
							+ '<!--Notes-->'
							+ '<label>Notes</label>'
							+ '<textarea name="message" style="height: 50px;"></textarea>'
							+ '<!--SUBMIT-->'
							+ '<input type="submit" id="send_request"'
							+ ' style="margin-top: 5px; max-width: 120px; color: #fff;'
							+ ' border: 1px solid transparent; border-radius: 4px;'
							+ ' background-color: #337ab7; border-color: #2e6da4;"'
							+ ' cursor: pointer; font-family: inherit; font-size: 14px;"'
							+ ' name="submitc" value="Send request">'
							+ '<label style="text-align: right;">Powered by <a href="https://call-back.io"><b>call-back.io</b></a></label>'
				+ '</form>'
			+ '</div>'
			+ '<script>'
				+ '$("#callback-button a").click(function(){'
					+ '$(this).hide();'
					+ '$("#callback-widget").fadeIn("slow");'
				+ '});'
				+ '$(window).on("click.Bst",function(e){'
					+ 'if ('
										+ '$("#callback-widget").has(event.target).length == 0'
										+ '&&'
										+ '!$("#callback-widget").is(event.target)'
										+ '&&'
										+ '!$("#callback-button").is(event.target)'
										+ '&&'
										+ '$("#callback-button").has(event.target).length == 0'
					+	'){'
						+ '$("#callback-widget").hide("slow");'
						+ '$("#callback-button a").show();'
					+ '}'
				+ '});'
			+ '</script>');
	});
